name: adda_gold
description: Adda Gold - Quiz and Reels learning app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  chewie: ^1.13.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9
  path_provider: ^2.1.1
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quizzes.json
    - assets/reels.json

